name: Next.js CI

on:
  push:
    branches:
      - main   # o la rama que uses como principal
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Chequear el código
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # o la versión que uses

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar pruebas
        run: npm test

      - name: Construir proyecto
        run: npm run build

      # Opcional: desplegar automáticamente, agregar pasos adicionales según tu flujo
